version: '3.7'

services:
  go-service-user-postgresql:
    container_name: go-service-user-postgresql
    image: service-user/go-app
    build: .
    environment:
#      DATABASE_URL: "host=go_db_service_user port=5432 user=postgres dbname=service-user password=root sslmode=disable"
      DSN: "host=go_db_service_user port=5432 user=postgres dbname=service-user password=postgres sslmode=disable"
    ports:
      - "3001:3001"
    depends_on:
      - go_db_service_user
  go_db_service_user:
    container_name: go_db_service_user
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: service-user
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
